project_id = "ppxmxiinavucugyojovl"

[functions.ensure-super-admin-account]
verify_jwt = false

[functions.bootstrap-super-admin]
verify_jwt = false

[functions.send-client-invite]
verify_jwt = false

[functions.send-team-invite]
verify_jwt = false

