// Reads recent error/warn audit events + recent failed AI runs and asks OpenAI to triage.
// Result is stored as an ai_action with action_type='code_suggestion' (review-only).
import { corsHeaders, jsonResponse, userClient, serviceClient, requireUser, getActivePrompt, OPENAI_API_KEY, OPENAI_BASE_URL, OPENAI_MODEL, logRun, estimateCost } from "../_shared/openai.ts";

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  try {
    if (!OPENAI_API_KEY) return jsonResponse({ error: "OPENAI_API_KEY missing" }, 500);
    const supa = userClient(req);
    const svc = serviceClient();
    const { userId } = await requireUser(supa, req);
    const { agency_id } = await req.json();
    if (!agency_id) return jsonResponse({ error: "Bad request" }, 400);

    // Only saas_admin can scan
    const { data: prof } = await supa.from("profiles").select("is_saas_admin").eq("id", userId).maybeSingle();
    if (!prof?.is_saas_admin) {
      const { data: mem } = await supa.from("agency_members").select("role").eq("agency_id", agency_id).eq("user_id", userId).maybeSingle();
      if (!mem || mem.role !== "agency_owner") return jsonResponse({ error: "Forbidden" }, 403);
    }

    const { data: events } = await svc.from("ai_audit_events")
      .select("level,event,payload,created_at")
      .in("level", ["warn", "error", "critical"])
      .order("created_at", { ascending: false }).limit(50);
    const { data: failedRuns } = await svc.from("ai_prompt_runs")
      .select("prompt_key,model,error_text,created_at")
      .eq("status", "error").order("created_at", { ascending: false }).limit(20);

    const promptRow = await getActivePrompt(svc, "maintainer_scan", agency_id);
    const userMsg = `Recent audit events:\n${JSON.stringify(events ?? [])}\n\nRecent failed AI runs:\n${JSON.stringify(failedRuns ?? [])}`;
    const t0 = Date.now();
    const resp = await fetch(`${OPENAI_BASE_URL}/chat/completions`, {
      method: "POST",
      headers: { Authorization: `Bearer ${OPENAI_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: promptRow?.model || OPENAI_MODEL,
        messages: [{ role: "system", content: promptRow?.content || "Triage SRE errors." }, { role: "user", content: userMsg }],
        temperature: 0.2,
      }),
    });
    if (!resp.ok) return jsonResponse({ error: await resp.text() }, resp.status);
    const data = await resp.json();
    const out = data.choices?.[0]?.message?.content || "";
    const tokensIn = data.usage?.prompt_tokens ?? 0;
    const tokensOut = data.usage?.completion_tokens ?? 0;
    const runId = await logRun(svc, {
      agency_id, user_id: userId, prompt_key: "maintainer_scan", prompt_version: promptRow?.version ?? null,
      model: promptRow?.model || OPENAI_MODEL, input_messages: [{ role: "user", content: userMsg }],
      output_text: out, tokens_in: tokensIn, tokens_out: tokensOut,
      latency_ms: Date.now() - t0, cost_usd: estimateCost(promptRow?.model || OPENAI_MODEL, tokensIn, tokensOut),
      status: "success", safety_flags: [],
    });
    const { data: action } = await supa.from("ai_actions").insert({
      agency_id, requested_by_user_id: userId,
      action_type: "code_suggestion",
      payload: { suggestion: out, sample_events_count: events?.length ?? 0 },
      reasoning: "Auto-generated by maintainer scan",
      run_id: runId,
      status: "pending",
    }).select("id").single();
    return jsonResponse({ ok: true, action_id: action?.id, output: out });
  } catch (e) {
    if (e instanceof Response) return e;
    return jsonResponse({ error: e instanceof Error ? e.message : "Unknown" }, 500);
  }
});
